/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class prictise_com_myapplication_model_Test */

#ifndef _Included_prictise_com_myapplication_model_Test
#define _Included_prictise_com_myapplication_model_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     prictise_com_myapplication_model_Test
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_prictise_com_myapplication_model_Test_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
