/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class prictise_com_myapplication_ndkImage_NdkImageUtils */

#ifndef _Included_prictise_com_myapplication_ndkImage_NdkImageUtils
#define _Included_prictise_com_myapplication_ndkImage_NdkImageUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     prictise_com_myapplication_ndkImage_NdkImageUtils
 * Method:    getNdkBitmap
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_prictise_com_myapplication_ndkImage_NdkImageUtils_getNdkBitmap
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
