/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class prictise_com_myapplication_model_JniTest */

#ifndef _Included_prictise_com_myapplication_model_JniTest
#define _Included_prictise_com_myapplication_model_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     prictise_com_myapplication_model_JniTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_prictise_com_myapplication_model_JniTest_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
